apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-a-prod-git-repo
spec:
  steps:
    - name: echo
      image: fedora
      script: |
        #!/usr/bin/env bash
        curl -u 'simonDelordtest:<GitHubPersonalToken>' https://api.github.com/user/repos -d '{"name":"prod-repo-app1"}'

