apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-a-dev-git-repo
spec:
  steps:
    - name: echo
      image: fedora
      script: |
        #!/usr/bin/env bash
        curl -u 'simonDelordtest:<GitHubPersonaltoken>' https://api.github.com/user/repos -d '{"name":"dev-repo-app1"}'

